### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by lukasmedia** [t3kpunk/Omniksol-PV-Logger#2]
python3 omniksol4kd.py 
  File "omniksol4kd.py", line 96
    print "ID     : {0}      Date:  {1}".format(msg.getID(),  time.strftime("%d-%m-%Y %H:%M:%S"))
          ^
SyntaxError: invalid syntax

**Comment by t3kpunk** [comment]
It's written in python2 for a special version of the wifi module. Sorry but the module stopped functioning a long time ago and I don't develop it any more.
